title: Default

columns:
  - width: 2/3
    sections:
      fields:
        type: fields
        fields:
          shortDescription:
            type: textarea
            buttons: false
          text:
            type: textarea
          redirect:
            type: toggle
      sections: sections/sections
  - width: 1/3
    sections:
      pages:
        type: pages
      files:
        type: files
