title: Site

sections:
  mainnav:
    type: pages
    status: listed
  orders:
    extends: sections/orders
  pages:
    type: pages
    status: unlisted
  meta:
    type: fields
    fields:
      metaTitle:
        type: text
      metaDescription:
        type: text
      legalLinks:
        type: pages
